
version: "0.1"
name: kot-duel
args:
    width : 63
    height: 88

template:
  - name: sheet-back
    steps:
      - action: sheet
        args:
          page: a4
          flip: true
          # align: top


  - name: sheet-large
    steps:
      - action: sheet
        args:
          page: a4
          # width : 70
          # height: 70
          # width : 63
          # height: 88

jobs:
  - name: sheet-s
    input: card-upscale/*.jpg
    output: sheet/card-s-*
    steps:
      - template: sheet-small

  - name: cut-1
    input: 1.jpg
    output: card/page-1-*
    steps:
      - cut-6-10-51

  - name: cut-2
    input: 2.jpg
    output: card/page-2-*
    steps:
      - cut-4-10-38
  
  