version: 1.0
name: 7 Wonders Duel
template:
  - name: ""
    steps: []
args:
  width: 44
  height: 68
  page: a4
jobs:
  - name: building
    output: pnp/building-*
    steps:
      - action: file
        file: buildings.png
      - cut-7-12
      - limit-73
      - action: sheet
  
  - name: back-building
    output: pnp/back-building-*
    steps:
      - part:
          - action: file
            file: building/building78.png
          - dup-23
      
      - part:
          - action: file
            file: building/building79.png
          - dup-23
      
      - part:
          - action: file
            file: building/building80.png
          - dup-20
      
      - part:
          - action: file
            file: building/building81.png
          - dup-7
      
      - action: sheet
        handlers: ['flip-x']
        line_color: white
        line_width: 1
  
  - name: wonder
    output: pnp/wonder-*
    steps:
      - action: file
        file: wonder.png
      - cut-4-5
      - limit-16
      - action: sheet
        width: 100
        height: 65
        page: a4
  
  - name: back-wonder
    output: pnp/back-wonder-*
    steps:
      - action: file
        file: wonder/wonder17.png
      - dup-8
      - action: sheet
        width: 100
        height: 65
        page: a4
  
  - name: token
    output: pnp/token-*
    steps:
      - action: dir
        dir: token
      - limit-15
      - part:
          - file token/token16.png
          - dup-15
      - action: sheet
        width: 28
        height: 28
        page: a4
